import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import crypto from 'node:crypto';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';
const native=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const flag=process.argv.indexOf('--source-root');const root=flag<0?path.resolve(native,'..'):path.resolve(process.argv[flag+1]);const ts=createRequire(path.join(root,'package.json'))('typescript');
const files=['src/scenes/rpg/TheaterInteriorScene.ts','src/modules/ChapterThreeTheaterController.ts','src/scenes/rpg/CanteenInteriorScene.ts'];const sources=Object.fromEntries(files.map(p=>[p,fs.readFileSync(path.join(root,p),'utf8')]));
function methods(file,names){const ast=ts.createSourceFile(file,sources[file],ts.ScriptTarget.Latest,true),found=[];function walk(n){if(ts.isMethodDeclaration(n)&&names.includes(n.name?.getText(ast)))found.push(n.getText(ast));ts.forEachChild(n,walk);}walk(ast);if(found.length!==names.length)throw Error('Changed topology '+file);return found.join('\n');}
const content=JSON.parse(fs.readFileSync(path.join(root,'src/data/chapter3-theater.content.json')));
function node(type,args=[]){const n={type,args,children:[],alpha:1};for(const m of ['setScrollFactor','setDepth','setStrokeStyle','setOrigin','setText','setVisible','setAlpha'])n[m]=(...v)=>{n[m.slice(3)]=v;if(m==='setAlpha')n.alpha=v[0];return n;};n.add=children=>{n.children.push(...(Array.isArray(children)?children:[children]));return n};n.destroy=()=>{};return n;}
const context=vm.createContext({theaterContent:content,record:node,THEATER_PROGRAM_ORDER:['spotlight','opening','finale'],CANTEEN_WORLD_DEPTH_OFFSET:120,Phaser:{Math:{Linear:(a,b,t)=>a+(b-a)*t},Geom:{Intersects:{RectangleToRectangle:(a,b)=>a.right>b.left&&a.left<b.right&&a.bottom>b.top&&a.top<b.bottom}}}});
const sceneMethods=methods(files[0],['openCodePanel','updateCodeDisplay','openProgramPanel','refreshProgramPanel','addPanelButton','closePanel','handlePanelKey']);
const controllerMethods=methods(files[1],['setProgramOrder','submitProgramOrder']);
const occ=methods(files[2],['updateOcclusion']);
const code=`class Source{constructor(state){this.state=state;this.events=[];this.panel=null;this.panelButtons=[];this.add={container:(...a)=>record('container',a),rectangle:(...a)=>record('rectangle',a),text:(...a)=>record('text',a)};this.runtime={getState:()=>this.state,emit:(id,payload)=>this.events.push({id,payload})};this.input={activePointer:{isDown:false}}} ${sceneMethods}}; class Controller{constructor(state){this.state=state;this.store={getState:()=>this.state,setState:f=>{this.state=f(this.state)}};this.events={emit:(id,payload)=>{}};} ${controllerMethods}}; class Occlusion{${occ}};globalThis.Source=Source;globalThis.Controller=Controller;globalThis.Occlusion=Occlusion;`;
vm.runInContext(ts.transpileModule(code,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,context);
const s={theaterHunt:{phase:'program_search',mode:'light',collectedProgramIds:['opening','spotlight','finale'],programOrder:[],programWrongAttempts:0},items:{},ui:{}};
const scene=new context.Source(s);scene.openCodePanel();for(const key of ['0','1','2','3','4'])scene.handlePanelKey({key});const keypad={draft:scene.codeInput,display:scene.codeDisplay.Text[0],buttons:scene.panelButtons.map(({x,y,width,height})=>({x,y,width,height}))};scene.handlePanelKey({key:'Backspace'});keypad.afterBackspace=scene.codeInput;scene.handlePanelKey({key:'Escape'});scene.openCodePanel();keypad.freshOpen=scene.codeInput;
scene.closePanel();scene.openProgramPanel();const programButtons=scene.panelButtons.map(({x,y,width,height})=>({x,y,width,height}));
const ctl=new context.Controller(structuredClone(s));const orders=[[],['opening'],['opening','opening'],['unknown'],['opening','spotlight','finale'],['opening','spotlight','finale','opening'],['spotlight','opening','finale']].map(order=>{const accepted=ctl.setProgramOrder(order);return {order,accepted,draft:structuredClone(ctl.state.theaterHunt.programOrder)}});ctl.setProgramOrder(['opening','spotlight','finale']);ctl.submitProgramOrder();const wrongDraft=structuredClone(ctl.state.theaterHunt.programOrder);
const occlusions=[];for(const anchor of [{x:1370,y:380},{x:1370,y:345},{x:1300,y:345},{x:1370,y:405}])for(const reduced of [true,false]){const o=new context.Occlusion(),visual=node('image'),bounds={left:1344,top:253,right:1618,bottom:407};o.reducedMotion=reduced;o.player={body:{bottom:anchor.y+39},getBounds:()=>({left:anchor.x-31.2,right:anchor.x+31.2,top:anchor.y-41.6,bottom:anchor.y+41.6}),setDepth(v){this.depth=v}};o.occlusionVisuals=[{id:'lost_found_front',bounds,sortY:407,image:visual}];o.updateOcclusion();occlusions.push({anchor,reduced,visible:visual.Visible[0],alpha:visual.alpha,softened:o.softenedOcclusionIds.includes('lost_found_front')});}
const out={sources:Object.fromEntries(files.map(p=>[p,crypto.createHash('sha256').update(sources[p]).digest('hex')])),keypad,programButtons,orders,wrongDraft,occlusions};const target=path.join(native,'tests/fixtures/c3_devices_source.json'),data=JSON.stringify(out,null,2)+'\n';if(process.argv.includes('--check')){if(fs.readFileSync(target,'utf8')!==data)throw Error('Source fixture stale');console.log('C3 devices fixture matches executed original TypeScript')}else{fs.writeFileSync(target,data);console.log(target)}
