extends "res://tests/test_c3_devices_controls.gd"
## Seeded C3 fixtures and real native controls, not an unseeded campaign or CUA.
const Motion=preload("res://scripts/presentation/c3_mixer_motion.gd")
const WorldMotion=preload("res://scripts/objects/canteen_mixer_performance.gd")
var rows: Array=[]
func check(ok: bool,label: String) -> void:
	super.check(ok,label);rows.append({"check":label,"passed":ok})
func run() -> void:
	if not OS.get_user_data_dir().begins_with("/tmp/"):
		push_error("Refusing mixer layer tests outside an isolated /tmp profile");quit(2);return
	state=root.get_node("State")
	var manifest: Dictionary=JSON.parse_string(FileAccess.get_file_as_string("res://assets/native/mixer/components.json"))
	var original: Dictionary=JSON.parse_string(FileAccess.get_file_as_string("res://data/native/canteen-object-layout.json"))
	for id in manifest.components:
		var part: Dictionary=manifest.components[id]
		check(FileAccess.get_sha256(part.path)==str(part.sha256),"original generated bytes match manifest: "+str(id))
		var image:=(load(part.path) as Texture2D).get_image()
		check(image.get_format()==Image.FORMAT_RGBA8 and image.get_size()==Vector2i(1536,1024),"real 1536x1024 alpha channel: "+str(id))
		check(image.get_pixel(1,1).a<0.02,"no opaque rectangle behind independent part: "+str(id))
	var glass_image:=(load(manifest.components.glass.path) as Texture2D).get_image()
	check(glass_image.get_pixel(768,500).a<0.08,"glass center is genuinely transparent, not a painted wood rectangle")
	var mixer_row: Dictionary={};var shelf_row: Dictionary={}
	for row in original.objects:
		if str(row.id)=="mixer_counter":mixer_row=row
		if str(row.id)=="drink_shelf":shelf_row=row
	check(str(mixer_row.asset)=="mixer_clean_worktop","only mixer uses clean worktop instead of three baked urns")
	check(str(shelf_row.asset)=="drink_station_cabinet","original drinks shelf keeps its original object identity")
	var node:=WorldMotion.new();root.add_child(node);node.set_process(false)
	var initial_scale: Vector2=Vector2.ONE*.36
	for outcome in ["success","bad",""]:
		node.item_id="sparklingWater";node.playing=true;node.outcome=outcome;node.shown_sequence=["blackCoffee","sparklingWater","lemonTea"];node.duration_ms=600
		for sample in [0,150,220,350,500,599]:
			node.sample_pose(sample)
			check(node.scale==initial_scale and node.glass_root.position==Vector2.ZERO and node.glass_root.scale==Vector2.ONE,"fixed world cup contact and scale: "+outcome+"/"+str(sample))
	check(node.glass_mask.clip_children==CanvasItem.CLIP_CHILDREN_ONLY,"liquid is clipped by a native perspective mask")
	check(node.liquid_parts.all(func(layer):return layer.get_parent()==node.glass_mask),"every drink layer belongs to the glass interior mask")
	node.queue_free();await frames()
	for dim in [Vector2i(1280,720),Vector2i(960,540),Vector2i(390,844),Vector2i(430,860),Vector2i(844,390)]:
		await setup("canteen_interior","canteen-mixer",dim)
		for id in controller.RECIPE:state.d.items[id]=true
		await open_world("canteen-mixer")
		var panel: Control=shell.c3_device_panel
		var motion: Node2D=panel.surface.motion
		check(motion.glass_sprite.region_rect.size*motion.glass_sprite.scale==Vector2(346,557)*(150.0/557.0),"glass uses uniform original aspect")
		var fixed_contact: Vector2=motion.position;var fixed_scale: Vector2=motion.scale
		var prompt_rect:=Rect2(panel.prompt_label.position,panel.prompt_label.size)
		var shelf_rect:=Rect2(panel.shelf_label.position,panel.shelf_label.size)
		var feedback_rect:=Rect2(panel.feedback_label.position,panel.feedback_label.size)
		check(feedback_rect==prompt_rect and not feedback_rect.intersects(shelf_rect),"one fixed footer swaps instruction and feedback, separate from the recorded clue")
		check(panel.prompt_label.visible and not panel.feedback_label.visible,"idle footer shows only one operation hint")
		check(panel.art_board.encloses(feedback_rect),"feedback stays within the bounded mixer panel")
		for message in [str(panel.session.drinks.ingredientAdded),str(panel.session.drinks.ingredientMissing),str(panel.session.drinks.mixerNeedShelf)]:
			shell._feedback(message);await frames()
			check(panel.feedback_label.visible and not panel.prompt_label.visible,"feedback replaces the instruction instead of adding another line")
			check(panel.feedback_label.get_minimum_size().y<=feedback_rect.size.y,"original feedback fits its reserved row without clipping: "+message)
		shell.world.subtitle="";shell.world.subtitle_left=0;await frames()
		check(panel.prompt_label.visible and not panel.feedback_label.visible,"cleared feedback restores the same single operation row")
		for label: Label in panel.labels:
			check(not Rect2(label.position,label.size).intersects(prompt_rect),"ingredient caption does not collide with instruction text")
			check(label.text in panel.session.NAMES.values(),"bottle caption contains only the drink name")
			check(label.get_minimum_size().y<=label.size.y,"drink name fits its reserved caption")
		if panel.compact_portrait:
			for foot: Vector2 in panel.surface.bottle_feet:
				check(foot.y<panel.art_board.position.y+panel.art_board.size.y*(800.0/1024.0),"portrait bottle contact stays on wood, above the original metal front edge")
		var snapshot: Dictionary=state.d.duplicate(true)
		panel.refresh();panel.configure_layout(panel.size,panel.compact_layout)
		check(state.d==snapshot,"refresh and resize cannot write a recipe or inventory")
		var chosen: int=panel.session.button_order.find("blackCoffee")
		var old_order: Array=panel.session.button_order.duplicate()
		await click(panel.slots[chosen]);motion.set_process(false)
		check(state.d.canteenHunt.drinkMixSequence==["blackCoffee"] and not state.d.items.blackCoffee,"physical coffee bottle submits exactly the original action")
		motion.sample_pose(180)
		check(motion.stream.visible and motion.bottle_sprite.texture!=null,"accepted first pour has independent real bottle and liquid stream")
		check(motion.position==fixed_contact and motion.scale==fixed_scale,"pour leaves the worktop and cup contact fixed")
		check(not panel.surface.bottles[chosen].visible,"active bottle has no duplicated stationary copy")
		check(motion.bottle_sprite.scale.x==motion.bottle_sprite.scale.y,"active bottle retains original uniform proportions")
		var a:=Rect2(panel.slots[chosen].position,panel.slots[chosen].size)
		check(a.encloses(Rect2(panel.surface.bottles[chosen].position,panel.surface.bottles[chosen].region_rect.size*panel.surface.bottles[chosen].scale)),"physical bottle remains the original slot target")
		var count: int=motion.observed_accepts
		await click(panel.slots[chosen])
		check(motion.observed_accepts==count and state.d.canteenHunt.drinkMixSequence==["blackCoffee"],"missing repeat feedback cannot consume or repeat an accepted pour")
		await key(KEY_ESCAPE)
		check(not is_instance_valid(shell.c3_device_panel) and state.d.canteenHunt.drinkMixSequence==["blackCoffee"],"cancel retains source partial glass and releases input")
		state.developer_mode=false
		check(state.save_game(),"partial source sequence saves to isolated profile")
		check(state.load_game(),"partial source sequence reloads from ordinary native save")
		state.developer_mode=true;await frames()
		await open_world("canteen-mixer");panel=shell.c3_device_panel
		check(panel.model.layers.size()==1 and panel.surface.motion.shown_sequence==["blackCoffee"],"reloaded popup reconstructs one source layer without replaying pour")
		for id in ["sparklingWater","lemonTea"]:await click(panel.slots[panel.session.button_order.find(id)])
		check(state.d.items.dailySpecialSparklingWater and state.d.canteenHunt.drinkMixAttemptCount==1 and panel.finishing,"third ingredient commits original success immediately before optional presentation")
		await create_timer(2.3).timeout;await frames()
		check(not is_instance_valid(shell.modal),"final native pour settles and returns to world automatically")
		await teardown()
	var path: String=OS.get_environment("MIXER_LAYER_REPORT")
	if not path.is_empty():
		var file:=FileAccess.open(path,FileAccess.WRITE);file.store_string(JSON.stringify({"checks":checks,"failures":errors,"actual_cua":false,"cases":rows},"\t"));file.close()
	print("MIXER_LAYER_SEPARATION ",checks," checks; ",errors," failures");quit(1 if errors else 0)
