extends SceneTree
const Door=preload("res://scripts/presentation/interior_door_layer.gd")
var failures:=0
var checks:=0
func _initialize() -> void: call_deferred("run")
func check(value: bool,label: String) -> void:
	checks+=1
	if not value: failures+=1; push_error(label)
func run() -> void:
	var door:=Door.new()
	var s: Dictionary={"native":{"scene":"canteen_interior","player":{"x":1349,"y":835},"settings":{"reduced_motion":false}},"canteenHunt":{"active":true,"phase":"tray_search"}}
	door.tick(0,s)
	check(door.sensor_open,"canteen source approach sensor")
	check(door.opening==Rect2(1305,795,88,105),"source map opening")
	check(door.duration_ms==460,"source duration")
	door.advance(174)
	check(not door.passable(),"before source .38 passage")
	door.advance(1)
	check(door.passable(),"rounded175ms source passage")
	door.advance(285)
	check(is_equal_approx(door.progress,1),"door fully open")
	check(is_equal_approx(door.leaf_rects()[0].size.x,44*.18),"folded source18percent width")
	check(door.leaf_rects()[1].end.x==1393,"right leaf remains hinged")
	s.native.player={"x":1140,"y":710}; door.tick(0,s)
	check(door.sensor_open,"source wider hold band prevents flicker")
	s.native.player.x=1134; door.tick(.46,s)
	check(not door.sensor_open and is_zero_approx(door.progress),"outside hold closes")
	s.native.player={"x":1349,"y":835}; s.canteenHunt.phase="exit_blocking"; door.tick(.5,s)
	check(not door.sensor_open,"active blocked phase cannot open")
	s.canteenHunt.active=false; door.tick(.46,s)
	check(door.sensor_open and door.passable(),"inactive source canteen permits exit")
	s.native.scene="theater_interior"; s.native.player={"x":836,"y":800}; door.tick(0,s)
	check(door.duration_ms==520 and door.sensor_open,"theater authored sensor and duration")
	check(door.opening==Rect2(748,845,176,70),"theater opening")
	check(door.source_rects[1]==Rect2(88,0,88,70),"theater exact right crop")
	door.advance(260)
	check(is_equal_approx(door.progress,.5) and is_equal_approx(door.visual_progress,.5),"source half sine tween")
	s.native.player.x=975; door.tick(0,s)
	check(door.sensor_open,"theater124/156 hysteresis")
	s.native.player.x=993; door.tick(.52,s)
	check(not door.sensor_open and is_zero_approx(door.progress),"theater closes outside156")
	door.configure("theater_interior",true)
	check(door.duration_ms==120,"source reduced motion cap")
	door.set_open(true); door.advance(30)
	check(is_equal_approx(door.progress,.25),"progress remains linear")
	check(is_equal_approx(door.visual_progress,(1-cos(PI*.25))/2),"leaf visual uses SineInOut")
	var before: float=door.visual_progress
	door.set_open(false); door.advance(0)
	check(is_equal_approx(door.visual_progress,before),"interrupted source tween retains current leaf transform")
	door.advance(120)
	check(is_zero_approx(door.visual_progress),"interrupted close reaches source closed pose")
	door.configure("dorm_hub")
	check(door.texture==null and not door.sensor_open,"scene cancellation discards door")
	door=null
	print("INTERIOR DOOR %d checks / %d failures" % [checks,failures])
	quit(1 if failures else 0)
