extends SceneTree
const Visual=preload("res://scripts/ui/phone_entry_visual.gd")
var shell: Control
var state: Node
var checks:=0
var failures:=0
var cues: Array=[]
var subtitles: Array=[]
func _initialize() -> void: run.call_deferred()
func frames(n: int=3) -> void:
	for i in range(n): await process_frame
func check(ok: bool,message: String) -> void:
	checks+=1
	if not ok: failures+=1; push_error("PHONE ENTRY: "+message)
func find_named(node: Node,name_value: String) -> Node:
	if node.name==name_value: return node
	for child: Node in node.get_children():
		var found:=find_named(child,name_value)
		if found!=null: return found
	return null
func click(button: Control) -> void:
	check(button!=null,"real clickable control exists")
	if button==null: return
	var point:=button.get_global_transform_with_canvas()*(button.size/2)
	var motion:=InputEventMouseMotion.new(); motion.position=point; root.push_input(motion)
	for down: bool in [true,false]:
		var event:=InputEventMouseButton.new(); event.position=point; event.button_index=MOUSE_BUTTON_LEFT; event.pressed=down; root.push_input(event)
	await frames()
func tick(ms: float) -> void:
	shell._process(ms/1000)
	await frames()
func fixture(page: String,network: String="campus_wifi") -> void:
	shell.audio_director.reset(); cues.clear(); subtitles.clear()
	state.d=state.initial(); state.developer_mode=true; state.d.native.page=page; state.d.networkMode=network
	shell._refresh(); await frames()
func session() -> RefCounted: return state.get_phone_entry_session()
func run() -> void:
	state=root.get_node("State"); state.developer_mode=true; state.d=state.initial()
	shell=load("res://scenes/main.tscn").instantiate(); root.add_child(shell); await frames(4); shell.set_process(false)
	shell.audio_director.cue_published.connect(func(id: String,_payload: Dictionary): cues.append(id))
	shell.audio_director.subtitle_timed.connect(func(text: String,_surface: String,_duration: float,_tone: String): subtitles.append({"text":text,"at":Time.get_ticks_msec()}))
	for viewport: Vector2i in [Vector2i(390,844),Vector2i(430,860),Vector2i(1440,900)]:
		root.size=viewport; shell.size=Vector2(viewport); await frames()
		await fixture("wechat")
		await click(find_named(shell.page_body,"WechatFriendAvatar"))
		check(session().friend_open and state.d.native.friend_scatter_pending,"avatar opens friend before slash puzzle")
		check(not find_named(shell.page_body,"FriendCodeMessage").visible,"message not shown before900ms")
		await tick(899); check(cues.count("native_wechat_message_arrived")==0,"no early message ping")
		await tick(1); check(cues.count("native_wechat_message_arrived")==1,"900ms arrival plays one source ping")
		check(shell.audio_director._procedural_beat("native_wechat_message_arrived",{}).cues[0].volume==.9,"arrival uses source default0.9 gain")
		await tick(1100); check(session().friend_phase==2 and cues.count("xy_attack")==1,"2000ms attack starts exactly once")
		var old_session:=session()
		state.act("c1_brightness",62); await frames()
		check(session()==old_session and session().friend_elapsed_ms==2000,"settings update preserves elapsed session")
		check(cues.count("xy_attack")==1,"rebuild never replays attack cue")
		shell._on_phone_page("control_center"); await tick(840)
		check(session().friend_elapsed_ms==2840 and state.d.ui.controlCenterOpen,"Control Center stays a sibling while clock continues")
		var visual: Node=find_named(shell.page_body,"FriendEntryVisual")
		check(visual.surface.position==Vector2.ZERO,"seven120ms local shakes terminate at2840ms")
		shell._on_phone_action("native_control_center_close",null); await frames()
		await click(find_named(shell.page_body,"FriendChatBack"))
		check(not state.d.flags.codeScattered and not session().friend_running,"back cancels incomplete scatter")
		check(shell.audio_director.voice_asset not in ["vo_legacy_xy_attack","vo_legacy_xy_laugh"],"back stops old scatter voice")
		await click(find_named(shell.page_body,"WechatRow_1"))
		check(session().friend_elapsed_ms==0,"reopen starts a fresh friend sequence")
		await tick(3999); check(not session().skip_friend(),"skip remains gated before4000ms")
		await tick(1); await click(find_named(shell.page_body,"FriendAttackSkip")); await tick(0)
		check(session().friend_skipped and session().friend_phase==3,"real eligible skip starts scatter/laugh")
		await tick(5379); check(not state.d.flags.codeScattered,"controller does not grant completion early")
		await tick(1); check(state.d.flags.codeScattered,"controller receives complete9380ms skipped proof")
		check(cues.count("native_wechat_message_arrived")==2 and cues.count("xy_laugh")==1,"reopened sequence has one arrival and one laugh")
		await fixture("tiyi","cellular")
		old_session=session(); await tick(1399)
		check(find_named(shell.page_body,"TiyiEntry")!=null,"allowed Tiyi stays loading until1400ms")
		shell._on_phone_page("control_center"); state.act("c1_network","campus_wifi"); await frames()
		await tick(1); shell._on_phone_action("native_control_center_close",null); await frames()
		check(session()==old_session and session().phase=="ready" and session().entry_allowed,"Tiyi mount snapshot survives network change and overlay")
		check(find_named(shell.page_body,"TiyiCount47")!=null,"accepted Tiyi still shows native main controls")
		await click(find_named(shell.page_body,"TiyiCount47")); check(state.d.digits.d2=="7","accepted entry removes duplicate live-network rejection")
		await fixture("tiyi","campus_wifi"); await tick(2999)
		state.act("c1_network","cellular"); await frames()
		check(not session().entry_allowed and state.d.flags.tiyiCrashCount==0,"blocked Tiyi cannot turn valid mid-mount")
		await tick(1); check(state.d.flags.tiyiCrashCount==1 and state.d.native.page=="tiyi","crash fact commits at3000ms before exit")
		check(shell.audio_director._procedural_beat("native_tiyi_crash",{}).cues[0].volume==.9,"crash uses source default0.9 gain")
		state.act("c1_tiyi_crash"); check(state.d.flags.tiyiCrashCount==1,"crash fact is idempotent across rebuild")
		await tick(330)
		var group: CanvasGroup=find_named(shell.page_body,"TiyiWholeAppCrash")
		check(group!=null and group.get_child_count()==1,"crash composites complete app including exit/text")
		check(is_equal_approx(group.transform.y.y,.92) and group.material.get_shader_parameter("contrast")==3.0,"whole-app source crash transform and filter apply")
		check(find_named(group,"TiyiLoadingExit").get_theme_font("font")==shell.phone.get_theme_default_font(),"CanvasGroup retains bundled phone font")
		await tick(289); check(state.d.native.page=="tiyi","crash return waits entire620ms")
		await tick(1); check(state.d.native.page=="phone_home","crash returns at3620ms")
		check(subtitles.is_empty(),"first crash uses controller feedback without taunt voice")
		await fixture("tiyi","campus_wifi"); await tick(3330); await click(find_named(shell.page_body,"TiyiLoadingExit")); await tick(2000)
		check(state.d.flags.tiyiCrashCount==1 and cues.count("sys_net_try")==0,"cancel during crash keeps earned count but cancels exit followup")
		state.open_page("tiyi"); await frames(); check(session().elapsed_ms==0,"Tiyi reentry starts one new mount clock")
		await fixture("zjuding","cellular")
		shell._on_phone_page("control_center"); await frames()
		check(find_named(shell.control_center,"ControlNetwork_wifi")!=null,"blocked app never replaces sibling Control Center with its loader")
		await click(find_named(shell.control_center,"ControlNetwork_wifi"))
		await click(find_named(shell.control_center,"PhoneNav_close")); await tick(3000)
		check(session().phase=="loading" and find_named(shell.page_body,"ZjudingReentryHint")!=null,"blocked Zjuding requires reentry even after WiFi restored")
		var hint: Control=find_named(shell.page_body,"ZjudingReentryHint")
		var exit_button: Control=find_named(shell.page_body,"ZjudingLoadingExit")
		check(hint.get_global_rect().end.y<=exit_button.get_global_rect().position.y,"blocked-entry hint does not overlap exit")
		check(exit_button.size.y*exit_button.get_global_transform().get_scale().y>=28,"source exit retains physical28px pointer floor")
		state.open_page("phone_home"); state.open_page("zjuding"); await frames(); await tick(1499)
		check(session().phase=="loading","Zjuding ready waits1500ms")
		await tick(1); check(session().phase=="ready" and find_named(shell.page_body,"ZjudingEntry")==null,"Zjuding opens at1500ms")
		state.d.actOne.phase="system_required"; shell._refresh(); await frames()
		old_session=session(); state.act("c1_network","cellular"); await frames()
		var battery: int=state.d.phoneBattery.percent
		await click(find_named(shell.page_body,"ZjudingSystemSeal"))
		check(state.d.native.page=="system_chat" and session()==old_session and session().phase=="ready","system conversation retains accepted Zjuding mount")
		check(state.d.phoneBattery.percent==battery,"conversation is same source app and does not consume extra battery")
		for line in range(5): await click(find_named(shell.page_body,"SystemDialogueAdvance"))
		check(state.d.native.page=="zjuding" and state.d.actOne.phase=="inventory_required","real system conversation completes through controller")
		check(session().phase=="ready" and session().elapsed_ms==1500,"conversation return does not restart accepted app")
		state.open_page("library_app"); await frames(); state.open_page("zjuding"); await frames()
		check(session().phase=="ready" and session().elapsed_ms==1500,"nested library return retains same source Zjuding component")
		state.d=state.d.duplicate(true); shell._refresh(); await frames()
		check(session().elapsed_ms==0 and not session().entry_allowed,"state replacement reloads mount snapshot with current network")
		check(shell.phone.size==Vector2(430,860),"all lifecycle changes preserve canonical phone frame")
	# Negative route/reload/modal and unskipped chronology cases use real Main.
	await fixture("wechat"); await click(find_named(shell.page_body,"WechatRow_1")); await tick(2100)
	state.open_page("phone_home"); await frames(); await tick(20000)
	check(not state.d.flags.codeScattered and not state.d.native.friend_scatter_pending,"leaving WeChat cancels pending fact and terminal callback")
	check(shell.audio_director.voice_asset not in ["vo_legacy_xy_attack","vo_legacy_xy_laugh"],"leaving WeChat stops old voice")
	await fixture("wechat"); await click(find_named(shell.page_body,"WechatRow_1")); await tick(2100)
	state.d=state.d.duplicate(true); shell._refresh(); await frames(); await tick(20000)
	check(not session().friend_open and not state.d.flags.codeScattered,"reload never resumes a stale scatter clock")
	check(shell.audio_director.voice_asset not in ["vo_legacy_xy_attack","vo_legacy_xy_laugh"],"same-page reload stops previous mount voice")
	await fixture("wechat"); await click(find_named(shell.page_body,"WechatRow_1")); await tick(13941)
	check(session().friend_phase==2,"unskipped attack follows11942ms authored audio duration")
	await tick(1); check(session().friend_phase==3,"unskipped laugh starts at13942ms")
	await tick(5379); check(not state.d.flags.codeScattered,"unskipped scatter remains gated before19322ms")
	await tick(1); check(state.d.flags.codeScattered,"unskipped source proof completes at19322ms")
	await fixture("tiyi","campus_wifi"); await tick(2500); state.open_page("phone_home"); await frames(); await tick(2000)
	check(state.d.flags.tiyiCrashCount==0,"cancel before3000ms never writes a crash fact")
	await fixture("tiyi","campus_wifi"); await tick(1800); state.d=state.d.duplicate(true); shell._refresh(); await frames()
	check(session().elapsed_ms==0,"reload starts Tiyi mount from zero")
	await tick(1200); check(state.d.flags.tiyiCrashCount==0,"old mount deadline cannot crash reopened app")
	await fixture("zjuding"); shell._show_settings(); await tick(1500)
	check(session().phase=="ready" and is_instance_valid(shell.modal),"settings modal does not pause source mount clock")
	shell._close_modal(); await frames()
	check(Visual.dot_offset(100,1)==0 and is_equal_approx(Visual.dot_offset(450,0),-10) and Visual.dot_offset(900,0)==0,"source loading dots use staggered900ms stepped hops")
	check(is_equal_approx(Visual.crash_sample(600).alpha,0) and is_equal_approx(Visual.crash_sample(600).scale_y,.02),"source crash ends collapsed and transparent before return")
	await fixture("library_app","cellular")
	check(find_named(shell.page_body,"ZjudingEntry")!=null,"direct nested library mount uses same Zjuding entry gate")
	state.act("c1_network","campus_wifi"); await tick(1600)
	check(not session().entry_allowed and find_named(shell.page_body,"ZjudingEntry")!=null,"nested route cannot bypass blocked mount by switching network")
	state.open_page("phone_home"); state.open_page("library_app"); await frames(); await tick(1500)
	check(session().phase=="ready" and find_named(shell.page_body,"ZjudingEntry")==null,"nested app remount accepts restored campus WiFi normally")
	# Taunt handoff follows actual first text display, not earlier request time.
	await fixture("tiyi","campus_wifi"); state.d.flags.tiyiCrashCount=2; shell.audio_director.set_process(false)
	await tick(3620)
	check(state.d.native.page=="phone_home" and state.d.flags.tiyiCrashCount==3,"third crash still uses same controller chronology")
	check(subtitles.is_empty() and not shell.audio_director.scheduled.any(func(e): return e.id=="sys_no_money"),"second taunt not timed before first is displayed")
	var first_at:=Time.get_ticks_msec(); shell.audio_director._process(0)
	check(subtitles.size()==1,"actual first taunt emits once")
	var second: Array=shell.audio_director.scheduled.filter(func(e): return e.id=="sys_no_money")
	check(second.size()==1 and int(second[0].at)-first_at>=3040 and int(second[0].at)-first_at<3100,"second taunt scheduled3040ms after actual first text")
	shell.audio_director.reset(); check(shell.audio_director.scheduled.is_empty(),"reset cancels pending taunt continuation")
	shell.audio_director.set_process(true)
	await shell.shutdown(); shell.queue_free(); await frames(3)
	print("Phone entry lifecycle: ",checks," checks, ",failures," failures")
	quit(1 if failures else 0)
