extends SceneTree
const Controller = preload("res://scripts/chapters/chapter1_2.gd")
var c = Controller.new()
var s: Dictionary
var checks = 0
var failures = 0
func expect(value: bool, label: String) -> void:
	checks += 1
	if not value:
		failures += 1
		push_error("FAILED: " + label)
func act(id: String, value: Variant = null) -> Dictionary:
	return c.dispatch(s,id,value)
func _initialize() -> void:
	s = JSON.parse_string(FileAccess.get_file_as_string("res://data/initial_state.json"))
	s.native = {"chapter":1,"page":"alarm","scene":"","mode":"light","selected_item":""}
	act("c2_recover_card")
	expect(not s.items.campusCard,"campus card locked in chapter one")
	act("c1_start_alarm")
	act("c1_dismiss_alarm")
	act("c1_wake")
	act("c1_enter_home")
	act("c1_absence")
	expect(s.digits.d1 == null,"absence digit gated by scattered code")
	act("c1_friend")
	expect(not s.flags.codeScattered,"friend interaction waits for full scatter presentation")
	act("c1_scatter_complete",{"phase":4,"elapsedMs":2000,"skipped":false})
	expect(not s.flags.codeScattered,"early scatter callback rejected")
	act("c1_scatter_complete",{"phase":4,"elapsedMs":19322,"skipped":false})
	act("c1_absence")
	act("c1_tiyi_digit")
	expect(s.digits.d2 == null,"sports digit refuses campus wifi")
	act("c1_network","移动数据")
	act("c1_tiyi_digit")
	act("c1_gear")
	expect(not s.flags.gearFallen,"gear requires auto rotation")
	act("c1_auto_rotate")
	act("c1_gear_rotated",{"elapsedMs":1500})
	act("c1_collect_gear")
	act("c1_avatar")
	expect(not s.flags.slashHalfDropped,"friend slash requires second auto rotation")
	act("c1_auto_rotate")
	act("c1_slash_rotated",{"elapsedMs":1100})
	for i in range(3): act("c1_avatar")
	act("c1_combine",["slashLine","reverseGear"])
	act("c1_tower","towerKey")
	expect(s.items.towerKey and not s.flags.towerOpened,"tower does not consume key during insertion")
	act("c1_tower_complete",{"elapsedMs":650})
	expect(not s.flags.towerOpened and s.items.towerKey,"insertion alone cannot open tower")
	act("c1_tower_complete",{"elapsedMs":1700})
	act("c1_headphone")
	expect(not s.items.headphone,"headphone requires music")
	act("c1_music")
	act("c1_headphone")
	act("c1_rain_drop")
	act("c1_combine",["waterDrop","headphone"])
	act("c1_plant","wateredHeadphone")
	act("c1_plant","fertilizer")
	act("c1_flower")
	expect(s.digits.d4 == null,"flower cannot bloom without lighting")
	act("c1_brightness",85)
	act("c1_plant_light")
	act("c1_flower")
	expect(s.digits.d4 == null and s.native.flower_eight_visible,"flower reveals digit before separate pickup")
	act("c1_collect_flower")
	expect(s.digits == {"d1":"0","d2":"7","d3":"9","d4":"8"},"authored four digits")
	act("c1_checkin","0798")
	expect(not s.flags.checkinDone,"checkin refuses cellular")
	act("c1_network","校园网")
	var result = act("c1_checkin","0798")
	expect(result.has("game") and s.flags.checkinDone,"checkin requests real interception")
	act("c1_intervention_result",{"interceptedCount":3,"lockHeldMs":1399,"failed":false,"dialogueCount":4,"whiteoutCompleted":true})
	expect(s.actOne.phase == "prologue","short hold rejected")
	act("c1_intervention_result",{"interceptedCount":3,"lockHeldMs":1400,"failed":false,"dialogueCount":0,"whiteoutCompleted":true})
	expect(s.actOne.phase == "prologue","exchange cannot be skipped")
	act("c1_intervention_result",{"interceptedCount":3,"lockHeldMs":1400,"failed":false,"dialogueCount":4,"whiteoutCompleted":true})
	expect(s.native.chapter == 2,"prologue reaches chapter two")
	act("c2_confront_system")
	expect(not s.actOne.dormHubUnlocked,"friend exchange gate")
	act("c2_friend_exchange")
	act("c2_confront_system")
	act("c2_enter_dorm")
	act("c2_recover_card")
	act("c2_movement_quest")
	act("c2_identify","错误 3250100755")
	expect(not s.actOne.characterNamed,"identity mismatch rejected")
	act("c2_identify","林星宇 3250100755")
	act("c2_exercise_result",{"failed":false,"points":9,"elapsedSeconds":540,"distanceMeters":2700})
	expect(not s.actOne.exerciseStarted,"partial virtual run rejected")
	act("c2_exercise_result",{"failed":false,"points":10,"elapsedSeconds":600,"distanceMeters":3000})
	expect(s.actOne.exerciseStarted and not s.actOne.movementEnabled,"automatic pacing is not manual control")
	act("c2_weather_drop")
	expect(s.items.weatherWater and not s.actOne.pushTriangleTaken,"water independent of triangle collection")
	act("c2_mentor","weatherWater")
	for i in range(3): act("c2_triangle")
	act("c1_combine",["pushTriangle","mentorLine"])
	act("c2_balance","rightArrow")
	expect(s.items.rightArrow and s.wallet.campusCardCents == 600,"balance shift retains reusable arrow")
	act("c2_login","3250100755 ZJU1897!")
	expect(not s.actOne.cc98Login.authenticated,"login requires card identity read")
	act("c2_card_identity")
	for i in range(3): act("c2_login","3250100755 wrong")
	expect(s.actOne.cc98Login.failureCount == 3 and s.actOne.cc98Login.lockUntilMs != null,"third failure starts persistent lock")
	act("c2_login","3250100755 ZJU1897!")
	expect(not s.actOne.cc98Login.authenticated,"correct password cannot bypass active lock")
	s.actOne.cc98Login.lockUntilMs = 0
	act("c2_login","3250100755 ZJU1897!")
	act("c2_purchase_gamepad")
	act("c2_purchase_gamepad")
	expect(s.wallet.campusCardCents == 0 and s.items.gamepad,"purchase deducts exactly once")
	act("c2_use_gamepad")
	act("c2_manual_input",{"moved":false,"distance":1,"input":"keyboard"})
	expect(not s.actOne.manualControlTested,"synthetic nonmovement cannot pass")
	act("c2_manual_input",{"moved":true,"distance":1,"input":"keyboard"})
	act("c2_dorm_exit")
	expect(s.actOne.phase == "reservation_briefing_required","manual input still requires source reservation briefing")
	act("c2_reservation_briefing")
	act("c2_reserve","基础馆 二层书库 022")
	expect(not s.actOne.canLeaveDorm,"wrong room cannot unlock exit")
	act("c2_reserve","基础馆 一层书库 022")
	act("c2_dorm_exit")
	expect(s.ui.libraryFinalsPhase == "library_route_unlocked","dorm exit opens library route")
	_library_tests()
	print("CHAPTER1_2_TESTS: %d checks; %d failures" % [checks, failures])
	quit(1 if failures else 0)

func _finish_library_story(id: String) -> void:
	var session: RefCounted=c.library.story_session(s)
	expect(session!=null and session.sequence_id==id,"source dialogue queued: "+id)
	if session==null: return
	var dialogue_host:=Node.new()
	expect(session.attach(s,dialogue_host),"source dialogue attaches: "+id)
	while session.status=="playing": session.advance(s,dialogue_host)
	act("lib_story_complete",session)
	expect(session.status=="consumed","full source dialogue acknowledged: "+id)
	dialogue_host.free()

func _library_tests() -> void:
	act("lib_enter")
	_finish_library_story("library_entered")
	act("lib_backpack")
	expect(not s.ui.libraryFinalsPuzzle.backpackInspected,"entrance record precedes backpack")
	act("lib_record")
	act("lib_backpack")
	_finish_library_story("library_occupied_seat_found")
	act("lib_note")
	act("lib_investigate","occupancyNote")
	_finish_library_story("cc98_occupation_post_opened")
	act("lib_catalog_terminal")
	act("lib_catalog_search","三分钟离座法")
	act("lib_catalog_select","three-minute-pause")
	expect(not s.items.callNumber755,"catalog distractor rejected")
	act("lib_catalog_select","three-minute-leave-method")
	_finish_library_story("library_catalog_match_found")
	act("lib_shelf")
	act("lib_read_rule")
	expect(not s.ui.libraryFinalsPuzzle.archivedRuleBriefingSeen,"reading rule does not acknowledge unseen dialogue")
	_finish_library_story("library_archived_rule_recovered")
	act("lib_front_desk")
	_finish_library_story("library_front_desk_proof_request")
	act("lib_photo")
	act("lib_dim_photo")
	expect(not s.ui.libraryFinalsPuzzle.photoDimmed,"photo requires dim brightness")
	act("c1_brightness",20)
	act("lib_dim_photo")
	act("lib_item_report")
	expect(not s.items.itemRecognitionReport,"report requires matching old photo")
	act("lib_view_photo","dorm_meal")
	act("lib_item_report")
	expect(not s.items.itemRecognitionReport,"decorative photo cannot certify report")
	act("lib_view_photo","seat_022_clue")
	act("lib_item_report")
	act("lib_scan")
	act("lib_scan_result",{"scanMs":719,"identityChecks":[false,false,false],"stamped":true})
	expect(not s.items.bagNonPersonProof,"incomplete scan rejected")
	act("lib_scan_result",{"scanMs":720,"identityChecks":[false,false,false],"stamped":true})
	for i in range(9): c.library.story_session(s,100)
	_finish_library_story("library_bag_nonperson_proof_issued")
	act("lib_receipt")
	expect(s.items.seat022Receipt and not s.items.rightArrow,"source receipt operation consumes arrow")
	act("c1_network","移动数据")
	act("lib_audit","7 47 2")
	expect(not s.items.libraryPresenceProof,"wrong proof count rejected")
	act("lib_audit","7 47 3")
	_finish_library_story("tiyi_presence_proof_issued")
	act("c1_network","校园网")
	for e in ["archived_leave_rule","bag_non_person_proof","seat_022_receipt","library_presence_proof"]: act("lib_upload",e)
	expect(s.ui.libraryFinalsPhase == "bd_briefing","four uploads required for BD")
	act("lib_bd_briefing")
	expect(not s.ui.libraryFinalsPuzzle.preBdBriefingSeen,"legacy briefing action cannot skip source dialogue")
	_finish_library_story("cc98_evidence_set_completed")
	for id in ["bd-notice-tens","bd-rule-count","bd-seat-tail","bd-arrival-minutes"]: act("lib_bd_select",id)
	act("lib_bd_submit")
	expect(s.ui.libraryFinalsPhase == "top_ten_rising","wrong BD source rejected")
	for id in ["bd-rule-count","bd-identity-zero","bd-seat-tail","bd-arrival-minutes"]: act("lib_bd_select",id)
	act("lib_bd_submit")
	_finish_library_story("cc98_top_ten_reached")
	act("lib_recovery_open")
	act("lib_generate_pass")
	expect(not s.items.seatReleasePass,"PASS requires recovery originals")
	for e in ["bag_non_person_proof","seat_022_receipt","library_presence_proof"]: act("lib_recovery_upload",e)
	act("lib_generate_pass")
	expect(not s.ui.libraryFinalsPuzzle.passBriefingSeen,"PASS generation does not acknowledge unseen dialogue")
	_finish_library_story("library_seat_release_pass_issued")
	act("lib_apply_pass")
	_finish_library_story("library_backpack_evicted")
	act("lib_sit")
	act("lib_dialogue_next")
	expect(s.native.chapter == 2,"one dialogue line cannot finish chapter")
	for i in range(19): act("lib_dialogue_next")
	expect(s.native.chapter == 2,"legacy dialogue buttons cannot bypass opening transition")
	var opening_host:=Node.new()
	var opening: RefCounted=c.library.scene_session(s)
	expect(opening.attach(s,opening_host),"controller opening attaches to native host")
	while opening.status=="playing": opening.advance_current(s,opening_host)
	act("lib_opening_complete",opening)
	opening_host.free()
	expect(s.native.chapter == 3 and s.canteenHunt.active,"full 022 conversation and transition unlock chapter three")
	expect(s.items.campusCard and s.digits.d1 == "0","chapter handoff preserves prior inventory and evidence")
