extends SceneTree
const Motion=preload("res://scripts/presentation/maintenance_cover_motion.gd")
const Phase=preload("res://scripts/ui/chapter4_phase_layers.gd")
const Chapter=preload("res://scripts/chapters/chapter4.gd")
var checks:=0
var failures:=0
func _initialize()->void:run.call_deferred()
func check(ok:bool,label:String)->void:
	checks+=1
	if not ok:failures+=1;push_error("MAINTENANCE_COVER: "+label)
func initial()->Dictionary:
	var s:Dictionary=JSON.parse_string(FileAccess.get_file_as_string("res://data/initial_state.json"))
	s.native={"chapter":4,"scene":"duan_yongping_temporal_maze","page":"c4_device","mode":"light","settings":{}}
	s.chapter4.prologueSeen=true;s.chapter4.phase="maintenance_repair";s.chapter4.timeState="2245_maintenance";s.chapter4.floor="A1";s.chapter4.mode="light";s.chapter4.guardMode="patrol"
	s.chapter4.factIds=["maintenance_incident_linked"]
	return s
func run()->void:
	var s:=initial();var m:=Motion.new();var c:=Chapter.new()
	var before:=JSON.stringify(s)
	check(m.sample(s,1000).angle_degrees==0,"Closed source pose is stable")
	for i in range(50):m.sample(s,1000+i)
	check(JSON.stringify(s)==before,"Reading presentation never grants a tool or fact")
	c.dispatch(s,"c4_cart_cover");check(not Motion.FACT in s.chapter4.factIds and m.sample(s,1100).angle_degrees==0,"Unprepared cover attempt does not animate")
	c.dispatch(s,"c4_diagnose",{"wheel_sound":"wrong","clock_jam":"gear_offset","oil_trace":"oil_shortage"})
	check(not s.items.shortPryBar and m.sample(s,1200).angle_degrees==0,"Wrong diagnosis does not invent pry bar or hinge motion")
	c.dispatch(s,"c4_diagnose",{"wheel_sound":"latch","clock_jam":"gear_offset","oil_trace":"oil_shortage"})
	check(s.items.shortPryBar and "cart_wheel_inspected" in s.chapter4.factIds,"Original diagnosis remains tool authority")
	c.dispatch(s,"c4_cart_cover")
	check(not s.items.shortPryBar and s.items.universalLubricatingOil and Motion.FACT in s.chapter4.factIds,"Original cover action owns consumption and oil grant immediately")
	check(m.sample(s,1300).angle_degrees==0,"Accepted hinge begins at zero degrees")
	m.tick(.05,s,1350);var a:float=m.sample(s,1350).angle_degrees
	check(a<0 and a>-21,"50ms is an intermediate bounded pose")
	m.tick(.05,s,1400);check(is_equal_approx(m.sample(s,1400).angle_degrees,-21),"100ms reaches half of original 42-degree angle")
	m.tick(.05,s,1450);check(m.sample(s,1450).angle_degrees<-21 and m.sample(s,1450).angle_degrees>-42,"150ms remains continuous")
	m.tick(.05,s,1500);check(m.sample(s,1500).angle_degrees==-42 and not m.sample(s,1500).moving,"200ms reaches exact original open pose")
	before=JSON.stringify(s);c.dispatch(s,"c4_cart_cover");check(JSON.stringify(s)==before and m.sample(s,1550).angle_degrees==-42,"Duplicate cover action cannot regrant or replay")
	var loaded:Dictionary=s.duplicate(true);check(m.sample(loaded,1600).angle_degrees==-42,"Ordinary replacement State restores terminal pose")
	var reopened:=Motion.new();check(reopened.sample(loaded,1600).angle_degrees==-42,"New scene with old completed fact never replays opening")
	s=initial();m=Motion.new();m.sample(s,2000);c.dispatch(s,"c4_diagnose",{"wheel_sound":"latch","clock_jam":"gear_offset","oil_trace":"oil_shortage"});c.dispatch(s,"c4_cart_cover");m.sample(s,2100)
	check(m.sample(s,2350).angle_degrees==-42,"Hidden interval resumes accepted terminal pose without stale motion")
	s=initial();m=Motion.new();m.sample(s,3000);c.dispatch(s,"c4_diagnose",{"wheel_sound":"latch","clock_jam":"gear_offset","oil_trace":"oil_shortage"});c.dispatch(s,"c4_cart_cover");m.sample(s,3100)
	s.native.settings.reduced_motion=true;check(m.sample(s,3100).angle_degrees==-42,"Reduced motion retains clear accepted before/after state")
	s.native.settings.reduced_motion=false;check(m.sample(s,3100).angle_degrees==-42,"Disabling reduced motion cannot rewind an already shown terminal pose")
	c.dispatch(s,"c4_cart_oil")
	check(not s.items.universalLubricatingOil and "cart_wheel_repaired" in s.chapter4.factIds and "clock_gear_repaired" in s.chapter4.factIds,"Original oil action retains both original repair facts")
	check(not m.sample(s,3100).visible and not m.sample(s,3100).moving,"Fast accepted oil does not wait for the cover's visual 200ms")
	# Production ordering: phase tick observes the fact before any draw/sample.
	s=initial();m=Motion.new();m.tick(.05,s,5000)
	c.dispatch(s,"c4_diagnose",{"wheel_sound":"latch","clock_jam":"gear_offset","oil_trace":"oil_shortage"});c.dispatch(s,"c4_cart_cover")
	m.tick(.05,s,5100)
	check(m.sample(s,5100).angle_degrees==0,"First accepting tick excludes the frame delta that preceded the fact")
	m.tick(.05,s,5150);check(m.sample(s,5150).angle_degrees<0 and m.sample(s,5150).angle_degrees>-21,"Tick-first ordering keeps 50ms intermediate")
	m.tick(.05,s,5200);check(is_equal_approx(m.sample(s,5200).angle_degrees,-21),"Tick-first ordering reaches half at 100ms")
	m.tick(.05,s,5250);check(m.sample(s,5250).moving,"Tick-first ordering cannot finish early at 150ms")
	m.tick(.05,s,5300);check(m.sample(s,5300).angle_degrees==-42 and not m.sample(s,5300).moving,"Tick-first ordering completes exactly at 200ms")
	var production:=Phase.new();s=initial();production.tick(.05,s)
	c.dispatch(s,"c4_diagnose",{"wheel_sound":"latch","clock_jam":"gear_offset","oil_trace":"oil_shortage"});c.dispatch(s,"c4_cart_cover");production.tick(.05,s)
	check(production.cover_motion.elapsed_ms==0 and production.cover_motion.sample(s,production.cover_motion.started_ms).angle_degrees==0,"Real phase tick preserves the accepted zero-degree first pose")
	var lifecycle:=Phase.new();s=initial();lifecycle.tick(0,s)
	c.dispatch(s,"c4_diagnose",{"wheel_sound":"latch","clock_jam":"gear_offset","oil_trace":"oil_shortage"});c.dispatch(s,"c4_cart_cover");c.dispatch(s,"c4_cart_oil");lifecycle.tick(.05,s)
	check(lifecycle.repair_ms<900,"Live accepted repair retains the existing 900ms cart motion")
	var restored:Dictionary=s.duplicate(true);lifecycle.tick(.01,restored)
	check(lifecycle.maintenance_sample(restored).cart==Vector2(1049,716),"Same-phase replacement owner settles previously completed cart")
	var unfinished:=initial();lifecycle.tick(0,unfinished)
	check(lifecycle.maintenance_sample(unfinished).cart==Vector2(1115,716) and not lifecycle.repaired and not lifecycle.cover_open,"Loading unfinished owner clears retired repair and cover presentation")
	lifecycle.tick(0,s)
	check(lifecycle.maintenance_sample(s).cart==Vector2(1049,716),"Returning to an earlier completed owner does not replay its retired motion")
	var layer:=Phase.new();s=initial();layer.tick(0,s)
	var rest:Dictionary=layer.cover_geometry(s,4000)
	check(rest.source_region==Rect2(88,100,28,16) and is_equal_approx(rest.scale,.65),"Cover uses bounded original wheel material with uniform cart scale")
	check(rest.pivot.is_equal_approx(Vector2(1125.4,703.975)),"Hinge pivot comes from original source frame and wheel region")
	layer.elapsed_ms=1340;var strained:Dictionary=layer.cover_geometry(s,4000)
	check(strained.pivot.is_equal_approx(rest.pivot+Vector2(-5,0)),"Cover stays attached during the existing five-pixel failed push")
	check(layer.maintenance_sample(s).offset==Vector2(-5,0),"Existing failed push is not reimplemented or changed")
	before=JSON.stringify(s)
	for invalid:float in [-5,INF,NAN]:m.tick(invalid,s,4000);check(is_finite(m.sample(s,4000).angle_degrees),"Bad render delta cannot corrupt pose")
	check(JSON.stringify(s)==before,"Timing, geometry and reduced samples remain state-read-only")
	print("MAINTENANCE_COVER_MOTION: %d checks; %d failures"%[checks,failures]);quit(1 if failures else 0)
